<?php

namespace AppBundle\Repository;

/**
 * HelloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelloRepository extends \Doctrine\ORM\EntityRepository
{
}
