<?php

namespace AppBundle\Repository;

/**
 * Operating_SystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Operating_SystemRepository extends \Doctrine\ORM\EntityRepository
{
}
