<?php

namespace AppBundle\Repository;

/**
 * OptionSubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionSubRepository extends \Doctrine\ORM\EntityRepository
{
}
