<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityManager;
/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
	public function __construct(){
	parent::__construct();	
	$this->em = $this->getContainer()->get('doctrine');
	$this->qd = $this->em->createQueryBuilder();
	}

	public function createSubcription(){
		
	}
}
