<?php

namespace AppBundle\Repository;

/**
 * SubscriptionInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
